# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NJWsChatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://chatbotregistry11.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5e1a670e1fc8462b92aaacc05a7a1fcd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1072cd904f3e4c18851171d047c72182 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_5e1a670e1fc8462b92aaacc05a7a1fcd }}/cc_project:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NJWsChatbot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_85026444dc5145c7b1547491efa4050f }}
        images: 'chatbotregistry11.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5e1a670e1fc8462b92aaacc05a7a1fcd }}/cc_project:${{ github.sha }}'